const employees = [
  {
    id: 1,
    firstName: "Amit Sharma",
    email: "e@e.com",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Implement JWT Authentication",
        description: "Add login/signup with JWT and refresh tokens",
        date: "2026-03-10",
        category: "Backend Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix CORS Issue",
        description: "Resolve CORS error between frontend and backend",
        date: "2026-03-08",
        category: "API Integration",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Debug Memory Leak",
        description: "Investigate and fix memory leak in Node.js server",
        date: "2026-03-07",
        category: "Performance Optimization",
      },
    ],
  },
  {
    id: 2,
    firstName: "Priya Mehta",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Build React Dashboard",
        description: "Create reusable components for admin dashboard",
        date: "2026-03-11",
        category: "Frontend Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "State Management Setup",
        description: "Integrate Redux Toolkit for global state",
        date: "2026-03-12",
        category: "Frontend Architecture",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Responsive UI Fixes",
        description: "Fix mobile responsiveness issues",
        date: "2026-03-09",
        category: "UI Optimization",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "API Error Handling",
        description: "Handle API failures gracefully in UI",
        date: "2026-03-06",
        category: "Error Handling",
      },
    ],
  },
  {
    id: 3,
    firstName: "Rahul Verma",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Write Unit Tests",
        description: "Add Jest tests for authentication module",
        date: "2026-03-13",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Code Refactoring",
        description: "Refactor old services into clean architecture",
        date: "2026-03-10",
        category: "Code Quality",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Optimize Database Queries",
        description: "Improve MongoDB aggregation performance",
        date: "2026-03-14",
        category: "Database Optimization",
      },
    ],
  },
  {
    id: 4,
    firstName: "Sneha Kapoor",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Setup CI/CD Pipeline",
        description: "Configure GitHub Actions for auto deployment",
        date: "2026-03-15",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Dockerize Application",
        description: "Create Dockerfile and docker-compose setup",
        date: "2026-03-10",
        category: "Containerization",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Server Crash Debugging",
        description: "Fix production server crash issue",
        date: "2026-03-08",
        category: "Production Issues",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Logging System",
        description: "Implement centralized logging using Winston",
        date: "2026-03-16",
        category: "Monitoring",
      },
    ],
  },
  {
    id: 5,
    firstName: "Vikram Singh",
    email: "employee5@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Implement Role-Based Access",
        description: "Add RBAC for admin and user roles",
        date: "2026-03-17",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "API Documentation",
        description: "Document APIs using Swagger",
        date: "2026-03-12",
        category: "Documentation",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Cache Optimization",
        description: "Implement Redis caching for APIs",
        date: "2026-03-18",
        category: "Performance",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "WebSocket Integration",
        description: "Add real-time updates using WebSockets",
        date: "2026-03-09",
        category: "Realtime Systems",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export function setLocalStorage() {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export function getLocalStorage() {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
}
